swagger: '2.0'
info:
  description: "This module contains a collection of YANG definitions for the configuration and identification of some common system properties within a device containing a NETCONF server.  This includes data node definitions for system identification, time-of-day management, user management, DNS resolver configuration, and some protocol operations for system management. Copyright (c) 2014 IETF Trust and the persons identified as authors of the code.  All rights reserved. Redistribution and use in source and binary forms, with or without modification, is permitted pursuant to, and subject to the license terms contained in, the Simplified BSD License set forth in Section 4.c of the IETF Trust's Legal Provisions Relating to IETF Documents (http://trustee.ietf.org/license-info). This version of this YANG module is part of RFC 7317; see the RFC itself for full legal notices."
  version: 0.0.1
  title: ietf-system@2014-08-06
  contact:
    name: API Support
    email: apiteam@swagger.io
    url: 'https://github.com/Redocly/redoc'
host: 172.20.0.1
basePath: /restconf/data
tags:
  - name: system
    description: System group configuration.
  - name: DNS-resolver
    description: Access to Petstore orders
  - name: user
    description: Operations about user
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  '/ietf-system:system/contact':
    get:
      tags:
        - system
      summary: '/ietf-system:system/contact (leaf)'
      description: The administrator contact information for the system. A server implementation MAY map this leaf to the sysContact MIB object.  Such an implementation needs to use some mechanism to handle the differences in size and characters allowed between this leaf and sysContact.  The definition of such a mechanism is outside the scope of this document.
      operationId: getContact
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  contact:
                    type: string
          examples:
            application/json:
              'ietf-system:system':
                contact: This new contact.
          headers: {}
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
      security: []
      parameters: []
  '/ietf-system:system/hostname':
    get:
      tags:
        - system
      summary: '/ietf-system:system/hostname'
      description: The name of the host.  This name can be a single domain label or the fully qualified domain name of the host.
      operationId: getHostname
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  hostname:
                    type: string
                    format: 'inet:domain-name'
                    description: ''
          examples:
            application/json:
              'ietf-system:system':
                hostname: Switch
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          headers: {}
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
      parameters: []
  '/ietf-system:system/location':
    get:
      tags:
        - system
      summary: '/ietf-system:system/location'
      description: The system location. A server implementation MAY map this leaf to the sysLocation MIB object.  Such an implementation needs to use some mechanism to handle the differences in size and characters allowed between this leaf and sysLocation.  The definition of such a mechanism is outside the scope of this document.
      operationId: getLocation
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  location:
                    type: string
                    description: ''
          examples:
            application/json:
              'ietf-system:system':
                location: New Location
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
  '/ietf-system:system/dns-resolver/options/timeout':
    get:
      tags:
        - DNS-resolver
      summary: '/ietf-system:system/dns-resolver/options/timeout'
      description: The amount of time the resolver will wait for a response from each remote name server before retrying the query via a different name server.
      operationId: getDnsTimeout
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      timeout:
                        type: integer
                        format: uint8
                        default: 5
                        example: 3
                        minimum: 0
                        maximum: 255
                        description: ''
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  options:
                    timeout: '3'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
      parameters:
        - type: string
          in: header
          name: Content-Type
  '/ietf-system:system/dns-resolver/options/attempts':
    get:
      tags:
        - DNS-resolver
      summary: '/ietf-system:system/dns-resolver/options/attempts'
      description: The number of times the resolver will send a query to all of its name servers before giving up and returning an error to the calling application.
      operationId: getDnsAttempts
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      attempts:
                        type: integer
                        format: uint8
                        default: 2
                        minimum: 0
                        maximum: 255
                        example: 2
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  options:
                    attmepts: '2'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
  '/ietf-system:system/dns-resolver/options':
    get:
      tags:
        - DNS-resolver
      summary: '/ietf-system:system/dns-resolver/options'
      description: Resolver options. The set of available options has been limited to those that are generally available across different resolver implementations and generally useful.
      operationId: getDnsOptions
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      timeout:
                        type: integer
                        format: uint8
                        default: 5
                        example: 3
                        minimum: 0
                        maximum: 255
                      attempts:
                        type: integer
                        format: uint8
                        default: 2
                        example: 2
                        minimum: 0
                        maximum: 255
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  options:
                    timeout: '3'
                    attempts: '2'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
    put:
      tags:
        - DNS-resolver
      summary: '/ietf-system:system/dns-resolver/options'
      description: Update DNS options
      operationId: putDnsOptions
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties: {}
      parameters:
        - in: body
          name: body
          schema:
            type: object
          description: ''
    parameters: []
  '/ietf-system:system/dns-resolver/search={domainName}':
    get:
      tags:
        - DNS-resolver
      summary: '/ietf-system:system/dns-resolver/search={domainName}'
      description: An ordered list of domains to search when resolving a host name.
      operationId: getSearchInfo
      parameters:
        - name: domainName
          in: path
          description: domain name to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      search:
                        type: string
                        format: 'inet:domain-name'
                      server:
                        $ref: '#/definitions/DnsServerUdpTcpDeclare'
                      options:
                        type: object
                        properties:
                          timeout:
                            type: integer
                            minimum: 0
                            maximum: 255
                          attemptes:
                            type: integer
                            minimum: 0
                            maximum: 255
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  search: quanta.corp
                  server:
                    - name: 10.243.16.11
                      udp-and-tcp:
                        address: 10.243.16.11
                    - name: 10.243.17.11
                      udp-and-tcp:
                        address: 10.243.17.11
                  options:
                    timeout: '3'
                    attempts: '2'
  '/ietf-system:system/dns-resolver/server={servername}':
    get:
      tags:
        - DNS-resolver
      summary: Find server name
      description: "List of the DNS servers that the resolver should query. When the resolver is invoked by a calling application, it sends the query to the first name server in this list.  If no response has been received within 'timeout' seconds, the resolver continues with the next server in the list. If no response is received from any server, the resolver continues with the first server again.  When the resolver has traversed the list 'attempts' times without receiving any response, it gives up and returns an error to the calling application. Implementations MAY limit the number of entries in this list."
      operationId: getServer
      parameters:
        - name: servername
          in: path
          description: server name to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      serrver:
                        $ref: '#/definitions/DnsServerUdpTcpDeclare'
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  server:
                    name: 10.243.16.11
                    udp-and-tcp:
                      address: 10.243.16.11
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
  '/ietf-system:system/dns-resolver/server={servername}/name':
    get:
      tags:
        - DNS-resolver
      summary: Find server name
      description: return server name
      operationId: getServerName
      parameters:
        - name: servername
          in: path
          description: server name to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      server:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  server:
                    name: 10.243.16.11
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
    parameters: []
  '/ietf-system:system/dns-resolver/server={servername}/udp-and-tcp':
    get:
      tags:
        - DNS-resolver
      summary: Find server udp-and-tcp info
      description: return server udp-and-tcp
      operationId: getServerUdpTcpAddress
      parameters:
        - name: servername
          in: path
          description: server name to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      server:
                        $ref: '#/definitions/DnsServerUdpTcpDeclare'
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  server:
                    name: 10.243.16.11
                    udp-and-tcp:
                      address: 10.243.16.11
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
  '/ietf-system:system/dns-resolver/server={servername}/udp-and-tcp/address':
    get:
      tags:
        - DNS-resolver
      summary: Find server udp-and-tcp address
      description: return server udp-and-tcp
      operationId: getServerUdpTcp
      produces:
        - application/json
      parameters:
        - name: servername
          in: path
          description: server name to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              'ietf-system:system':
                type: object
                properties:
                  dns-resolver:
                    type: object
                    properties:
                      server:
                        $ref: '#/definitions/DnsServerUdpTcpDeclare'
          examples:
            application/json:
              'ietf-system:system':
                dns-resolver:
                  server:
                    name: 10.243.16.11
                    udp-and-tcp:
                      address: 10.243.16.11
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResDeclare'
          examples:
            application/json:
              'ietf-restconf:errors':
                error:
                  error-type: application
                  error-tag: invalid-value
                  error-message: Restconf Message is not valid
securityDefinitions: {}
definitions:
  DnsServerUdpTcpDeclare:
    type: object
    properties:
      name:
        type: string
        description: An arbitrary name for the DNS server.
      udp-and-tcp:
        type: object
        description: Contains UDP- and TCP-specific configuration parameters for DNS.
        properties:
          address:
            type: string
            description: The address of the DNS server.
          port:
            type: integer
            default: 53
            description: The UDP and TCP port number of the DNS server.
            x-deprecated: true
  ErrorResDeclare:
    type: object
    properties:
      error:
        type: object
        properties:
          error-type:
            type: string
          error-tag:
            type: string
          error-message:
            type: string
